# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
input_file = "output_data/cities.csv"

csv = pd.read_csv(input_file)

csv.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,N훮l큰t,30.33,10.85,81.00,24,0,6.40,LY,1594951957
1,1,Camacha,33.08,-16.33,68.00,88,20,8.05,PT,1594951957
2,2,Richards Bay,-28.78,32.04,52.38,74,0,3.56,ZA,1594951957
3,3,Bredasdorp,-34.53,20.04,44.60,87,0,6.93,ZA,1594951957
4,4,Punta Arenas,-53.15,-70.92,30.20,86,0,4.70,CL,1594951957

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
# Configure google maps
gmaps.configure(api_key=g_key)

# Create variables for Location and Humidity
locations=csv[["Lat", "Lng"]]
Humidity= csv["Humidity"]

# Define the heatmap parameters
fig=gmaps.figure()

# Create the heat layer
heat_layer=gmaps.heatmap_layer(locations, weights=Humidity, dissipating= False, max_intensity=250, point_radius=3)

#Add Layer
fig.add_layer(heat_layer)

#Display the map
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
# Personal preference
# 70> but not higher 80 
# 60< Humidity
# Lat > 30

temp_df=csv[(csv["Max Temp"]>=70)&(csv["Max Temp"]<80)&(csv["Humidity"]<60)& (csv["Lat"]>30)]
temp_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
80,80,Yumen,40.28,97.20,72.88,37,95,13.20,CN,1594951798
142,142,Yangi Marg`ilon,40.43,71.72,78.80,29,100,2.24,UZ,1594951971
170,170,Mata,40.68,-7.46,75.00,41,100,4.00,PT,1594951974
221,221,Herat Province,34.50,62.00,77.00,38,20,9.17,AF,1594951979
223,223,Portland,45.52,-122.68,79.00,47,20,12.75,US,1594951758
225,225,Xining,36.62,101.77,75.00,52,23,0.22,CN,1594951979
248,248,Moose Factory,51.26,-80.61,75.20,53,20,21.92,CA,1594951982
254,254,Wasilla,61.58,-149.44,73.40,49,40,3.36,US,1594951982
269,269,Yinchuan,38.47,106.27,77.25,50,3,2.77,CN,1594951984
279,279,Espa챰ola,35.99,-106.08,73.99,49,40,11.54,US,1594951882
318,318,Cabra,37.47,-4.44,78.80,39,0,6.93,ES,1594951989
361,361,Koutsouras,35.03,25.95,77.00,50,0,11.01,GR,1594951993
481,481,Derzhav카nsk,51.10,66.32,70.88,50,0,14.27,KZ,1594952009
490,490,Erenhot,43.65,111.98,76.17,35,99,16.71,CN,1594952010
526,526,Linxia Chengguanzhen,35.60,103.21,71.15,54,0,1.39,CN,1594952015

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
#create df of hotel name, along with city, count, geocod(lat,long)
hotel_df=temp_df[["City","Country", "Lat", "Lng"]].copy()
hotel_df["Hotel Names"]= ""
hotel_df

                     City Country    Lat     Lng Hotel Names
80                  Yumen      CN  40.28   97.20
142       Yangi Marg`ilon      UZ  40.43   71.72
170                  Mata      PT  40.68   -7.46
221        Herat Province      AF  34.50   62.00
223              Portland      US  45.52 -122.68
225                Xining      CN  36.62  101.77
248         Moose Factory      CA  51.26  -80.61
254               Wasilla      US  61.58 -149.44
269              Yinchuan      CN  38.47  106.27
279              Espa챰ola      US  35.99 -106.08
318                 Cabra      ES  37.47   -4.44
361            Koutsouras      GR  35.03   25.95
481           Derzhav카nsk      KZ  51.10   66.32
490               Erenhot      CN  43.65  111.98
526  Linxia Chengguanzhen      CN  35.60  103.21

In [21]:
#Define variables
radius=8000
gtype="lodging"

#Making query calls for top Hotel

base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params={"radius": radius, "types": gtype,"key": g_key}



#Using .itterrow()

for index, row in hotel_df.iterrows():
    
    #get city name in each row
    location=row[["Lat","Lng"]].values

    #add a keyword to my params dictionary
    params["location"]=f'{location[0]},{location[1]}'

    #Make a query url and API call
    query_url=requests.get(base_url, params=params).json()
    
    #extract results
    results=query_url['results']
    
    #Add the information into the Hotel Names column
    try:
        hotel_df.loc[index, "Hotel Names"]=results[0]['name']
    except (KeyError, IndexError):
        print("There is a missing field. Skipping...")

There is a missing field. Skipping...
There is a missing field. Skipping...

In [22]:
hotel_df=hotel_df[hotel_df["Hotel Names"]!= ""]

In [23]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Names}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [24]:
# Add marker layer ontop of heat map
markers=gmaps.marker_layer(locations, info_box_content=hotel_info)


# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))